[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "stook"
version = "0.0.1"
dependencies = [
    "numpy",
    "pandas",
    "plotly",
    "seaborn",
    "networkx",
    "scikit_learn",
    "scipy",
    "vectorbt",
]

[tool.setuptools]
package-dir = {"" = "src"}


